### ISSUE TITLE
How to obtain file conllpp_test_rev.txt 

### ISSUE THREAD

**Issue by Dimiftb** [wzhouad/NLL-IE#1]
Hi there, 

I'm trying to replicate your results and use your model as baselines. I've followed the instructions on obtaining the data and got all files except file conllpp_test_rev.txt. 

I even ran the example.sh from the CrossWeigh repo, however there are no files generated with that name. Could you please provide the file, or specific instructions on how to obtain it? Thanks.

**Comment by wzhouad** [comment]
The conlpp_test_rev.txt is the revisited CoNLL03 dataset. I've fixed the file structure in the readme.

**Comment by Dimiftb** [comment]
Thank you closing this.
